version: v4
pipelines:
  name: Test 1
  endpoint:
    access: ENV_($ENDPOINT)
    credentials:
      type: Basic
      username: ENV_($GRAPHDB_USERNAME)
      password: ENV_($GRAPHDB_PASSWORD)
  steps:
    - insert-quad.ru
