name: Build and release on NPM

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  id-token: write # Required for OIDC
  contents: write # Required to create release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false # never use caching in release builds

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm publish --provenance --access public

      - name: Make release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
